### ISSUE TITLE
`suggest lands` not working

### ISSUE THREAD

**Issue by tooomm** [arxanas/drafts.ninja#37]
Clicking the button does nothing. `reset lands` works though.

**Comment by arxanas** [comment]
I can't reproduce this. Are you sure that you've seen the "deck size" field correctly?

**Comment by tooomm** [comment]
I get this:
![suggest lands](https://cloud.githubusercontent.com/assets/9874850/16801172/6e3a0032-48f9-11e6-8482-117326df98e7.png)

**Comment by arxanas** [comment]
How many cards are in your maindeck? What browser are you using? Can you open the JS console and check for any errors?

**Comment by tooomm** [comment]
I use chrome and firefox and I think it wasn't working for both. Chrome is not the most recent version though.
If you tell me how to use the consoles in these programs and which info you exactly need, I'm happy to report any errors!

**Comment by tooomm** [comment]
moved to new repo: https://github.com/dr4fters/dr4ft/issues/55
